// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTFrDe_PfZAqVdSMhzCnKwk588GQzFY9I',
    appId: '1:288739641258:web:fcfe0c14b9a187a385cdd3',
    messagingSenderId: '288739641258',
    projectId: 'fitsync-app-50831',
    authDomain: 'fitsync-app-50831.firebaseapp.com',
    storageBucket: 'fitsync-app-50831.appspot.com',
    measurementId: 'G-4NGTS87TFQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAxaL9XIp2Y7Gwyd1uwqUEhUO8E1nX1-Q',
    appId: '1:288739641258:android:23756547e9e3060385cdd3',
    messagingSenderId: '288739641258',
    projectId: 'fitsync-app-50831',
    storageBucket: 'fitsync-app-50831.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoIhxd2vh1BCcu1NB2O37r2xm5WPgvKj4',
    appId: '1:288739641258:ios:ebb5359e8c0ce40985cdd3',
    messagingSenderId: '288739641258',
    projectId: 'fitsync-app-50831',
    storageBucket: 'fitsync-app-50831.appspot.com',
    androidClientId: '288739641258-du9i1j0q564k9k1s5nblf0lhupuf514o.apps.googleusercontent.com',
    iosClientId: '288739641258-mfugaeihv433kvr9vgblmf8686q2krfc.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitsync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoIhxd2vh1BCcu1NB2O37r2xm5WPgvKj4',
    appId: '1:288739641258:ios:2d2979aa75d694da85cdd3',
    messagingSenderId: '288739641258',
    projectId: 'fitsync-app-50831',
    storageBucket: 'fitsync-app-50831.appspot.com',
    androidClientId: '288739641258-du9i1j0q564k9k1s5nblf0lhupuf514o.apps.googleusercontent.com',
    iosClientId: '288739641258-gif5sagfm596d5a636m78nnddivk0o2l.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitsync.RunnerTests',
  );
}
