// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZG5f5zuchWTyi5ejqqeUo-7l0SGPw7dw',
    appId: '1:615688637589:web:fd678f4349d019bc42df9c',
    messagingSenderId: '615688637589',
    projectId: 'fit-sync-8544d',
    authDomain: 'fit-sync-8544d.firebaseapp.com',
    storageBucket: 'fit-sync-8544d.appspot.com',
    measurementId: 'G-FCQP4X5WT6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwLFLTXnHWNICn61rCQM9WYN17LUszJ0k',
    appId: '1:615688637589:android:d5c3f227548265d142df9c',
    messagingSenderId: '615688637589',
    projectId: 'fit-sync-8544d',
    storageBucket: 'fit-sync-8544d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOwu5XJg6Cms0F6LaPwan20n_xDZBMC7s',
    appId: '1:615688637589:ios:42f20b4ae728019142df9c',
    messagingSenderId: '615688637589',
    projectId: 'fit-sync-8544d',
    storageBucket: 'fit-sync-8544d.appspot.com',
    iosBundleId: 'com.example.fitsync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOwu5XJg6Cms0F6LaPwan20n_xDZBMC7s',
    appId: '1:615688637589:ios:a35e827ef94f655542df9c',
    messagingSenderId: '615688637589',
    projectId: 'fit-sync-8544d',
    storageBucket: 'fit-sync-8544d.appspot.com',
    iosBundleId: 'com.example.fitsync.RunnerTests',
  );
}
